
all:
	wget --auth-no-challenge http://auction.dmm.com/_js/jquery.js
	wget --auth-no-challenge http://auction.dmm.com/_js/auction.js
	wget --auth-no-challenge http://auction.dmm.com/_js/effect.js
